targets:
  $default:
    builders:
      freezed:freezed:
        enabled: true
        generate_for:
          include:
            - lib/data/model/**.dart
            - lib/domain/entity/**.dart
      json_serializable:
        options:
          explicit_to_json: true
      auto_route_generator:auto_route_generator:
        generate_for:
          - lib/presentation/pages/**_page.dart
          - lib/routes/app_router.dart
