name: mint
description: Mint - Online consultations with psychologists
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  auto_route: ^7.5.0
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_libphonenumber: ^2.1.4
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  injectable: ^2.1.2
  intl: ^0.18.0
  meta: ^1.9.1
  pinput: ^2.2.31
  rxdart: ^0.27.7

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  dart_code_metrics: ^5.7.5
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.1.6
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter_gen:
  integrations:
    flutter_svg: true

  fonts:
    outputs:
      class_name: MintFontFamily
  colors:
    outputs:
      class_name: MintColors
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: SfProDisplay
      fonts:
        - asset: assets/fonts/sf_pro_display/SFProDisplay-Regular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
