name: mint
description: Mint - Online consultations with psychologists
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audio_waveforms: ^1.0.4
  auto_route: ^7.5.0
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cloud_firestore: ^4.8.2
  cloud_functions: ^4.3.4
  emoji_picker_flutter: ^1.6.1
  file_picker: ^5.3.3
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.9
  flutter_firebase_chat_core:
    git:
      url: https://github.com/wuffeel/flutter_firebase_chat_core.git
      ref: main
  flutter_libphonenumber: ^2.1.4
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar:
    git:
      url: https://github.com/wuffeel/flutter_rating_bar.git
      ref: master
  flutter_screenutil: ^5.8.4
  flutter_sticky_header: ^0.6.5
  flutter_stripe: ^9.3.0
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  http: ^0.13.6
  image_picker: ^1.0.1
  injectable: ^2.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  mask_text_input_formatter: ^2.5.0
  meta: ^1.9.1
  open_filex: ^4.3.2
  path_provider: ^2.0.15
  pinput: ^2.2.31
  rxdart: ^0.27.7
  shimmer: ^3.0.0
  sliver_tools: ^0.2.12
  table_calendar: ^3.0.9
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^7.1.1
  bloc_test: ^9.1.2
  build_runner: ^2.4.6
  dart_code_metrics: ^5.7.5
  flutter_gen_runner: ^5.3.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.5
  injectable_generator: ^2.1.6
  json_serializable: ^6.7.1
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter_gen:
  integrations:
    flutter_svg: true

  fonts:
    outputs:
      class_name: MintFontFamily
  colors:
    outputs:
      class_name: MintColors
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/svg/
    - assets/fonts/

  fonts:
    - family: SfProDisplay
      fonts:
        - asset: assets/fonts/sf_pro_display/SFProDisplay-Regular.ttf
          weight: 400
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/proxima_nova/ProximaNova-Regular.ttf
          weight: 400
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/inter/Inter-Black.ttf
          weight: 900
